/* Auto-generated by the Program Module-Builder. */
package org.axcommunity.niagara.logic;

import javax.baja.log.Log;
import javax.baja.status.*;
import javax.baja.sys.*;


public class BSuperOr
extends BComponent implements Runnable
{

	////////////////////////////////////////////////////////////////
	// Property "toNull"
	////////////////////////////////////////////////////////////////
	public static final Property toNull = newProperty(0|Flags.EXECUTE_ON_CHANGE, (BValue)BBoolean.TYPE.getInstance(), null);
	public boolean getToNull() { return getBoolean(toNull); }
	public void setToNull(boolean v) { setBoolean(toNull, v, null); }

	////////////////////////////////////////////////////////////////
	// Property "time"
	////////////////////////////////////////////////////////////////
	public static final Property time = newProperty(0, BRelTime.make(1000l),BFacets.make(BFacets.SHOW_MILLISECONDS, true));
	public BRelTime getTime() { return (BRelTime)get(time); }
	public void setTime(BRelTime v) { set(time,v,null); }
	
	////////////////////////////////////////////////////////////////
	// Property "numberOfValues"
	////////////////////////////////////////////////////////////////
	public static final Property numberOfValues = newProperty(0|Flags.HIDDEN|Flags.READONLY, new BStatusNumeric(), null);
	public BStatusNumeric getNumberOfValues() { return (BStatusNumeric)get(numberOfValues); }
	public void setNumberOfValues(BStatusNumeric v) { set(numberOfValues, v, null); }

	////////////////////////////////////////////////////////////////
	// Property "Out"
	////////////////////////////////////////////////////////////////
	public static final Property Out = newProperty(0|Flags.READONLY|Flags.SUMMARY, new BStatusBoolean(), null);
	public BStatusBoolean getOut() { return (BStatusBoolean)get(Out); }
	public void setOut(BStatusBoolean v) { set(Out, v, null); }

	////////////////////////////////////////////////////////////////
	// Property "OutRev"
	////////////////////////////////////////////////////////////////
	public static final Property OutRev = newProperty(0|Flags.READONLY|Flags.SUMMARY, new BStatusBoolean(), null);
	public BStatusBoolean getOutRev() { return (BStatusBoolean)get(OutRev); }
	public void setOutRev(BStatusBoolean v) { set(OutRev, v, null); }

	////////////////////////////////////////////////////////////////
	// Action "execute"
	////////////////////////////////////////////////////////////////
	public static final Action execute = newAction(0|Flags.ASYNC|Flags.HIDDEN, null, null);
	public void execute(){ invoke(execute, null, null); }
	public void doExecute() throws Exception
	{
		try { onExecute(); }
		catch (Throwable t) { throw new Exception(t); }
	}
	
	////////////////////////////////////////////////////////////////
	// Action "calculate"
	////////////////////////////////////////////////////////////////
	public static final Action calculate = newAction(0|Flags.ASYNC|Flags.HIDDEN, null, null);
	public void calculate(){ invoke(calculate, null, null); }
	public void doCalculate() throws Exception
	{
		try { onCalculate(); }
		catch (Throwable t) { throw new Exception(t); }
	}

	////////////////////////////////////////////////////////////////
	// Action "VariableCount"
	////////////////////////////////////////////////////////////////
	public static final Action VariableCount = newAction(0, (BValue)BDouble.TYPE.getInstance(), null);
	public void VariableCount(BDouble v){ invoke(VariableCount, v, null); }
	public void doVariableCount(BDouble v) throws Exception
	{
		try { onVariableCount(v); }
		catch (Throwable t) { throw new Exception(t); }
	}
	
	////////////////////////////////////////////////////////////////
	// Topic 'True'
	////////////////////////////////////////////////////////////////
	public static final Topic True = newTopic(0);
	public void fireTrue(BBoolean event){fire(True,event,null);}
	
	////////////////////////////////////////////////////////////////
	// Topic 'False'
	////////////////////////////////////////////////////////////////
	public static final Topic False = newTopic(0);
	public void fireFalse(BBoolean event){fire(False,event,null);}
	
	

	////////////////////////////////////////////////////////////////
	// BComponent Overrides
	////////////////////////////////////////////////////////////////
	public void started() throws Exception { try { onStart(); } catch(Throwable t) { throw new Exception(t); } }
	public void stopped() throws Exception { try { onStop(); } catch(Throwable t) { throw new Exception(t); } }
	public void changed(Property prop, Context cx)
	{
		// super.changed(prop, cx);
		if(!Sys.atSteadyState() || !isRunning())return;
		if(prop.toString().startsWith("In") || prop.toString().startsWith("toNull")) 
		{
			try
			{
				logger.trace("\n\t\t" + getSlotPath()	+ "\n\t\t'" + prop.toString() + "'    value has changed.\n");
				execute();
			}
			catch (Exception e) 
			{
				logger.error("\n\t\t" + getSlotPath()	+ "\n\t\t'changed()' method had an error.\n\t\t" + e.getMessage() + "\n\t\t" + e.getStackTrace());
			}
		}
		// if (Flags.isExecuteOnChange(this, prop)) execute();
	}


	////////////////////////////////////////////////////////////////
	// Runnable
	////////////////////////////////////////////////////////////////
	public void run() { System.out.println("Source BProgram did not override run(). Exiting thread."); }

	////////////////////////////////////////////////////////////////
	// Access
	////////////////////////////////////////////////////////////////
	public final BComponent getComponent() { return this; }
	public final BComponent getProgram() { return this; }

	////////////////////////////////////////////////////////////////
	// Utils
	////////////////////////////////////////////////////////////////
	/** Print a string to standard out without a trailing new-line. */
	public void print(String s) { System.out.print(s); System.out.flush(); }

	/** Print a string to standard out with a trailing new-line. */
	public void println(String s) { System.out.println(s); }

	////////////////////////////////////////////////////////////////
	// ProgramBase Stubs
	////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////
	// BProgram Source Code
	////////////////////////////////////////////////////////////////

	/**   
	This is an OrGate on steriods.  Created 02/02/11 By: CMH (XENCOM Energy Management)
	This OrGate can be generated to accommodate any number of points. 

	1. Right Click on the program and Select "Action" then "VariableCount". Choose how many
	variables you would like to compare. (If you need more later, just increase the number.
	WARNING! If you decrease the number of slots, you could lose links. The program will
	start by deleting the highest number slot and continue until the correct amount of
	slots remain. You will not lose any slots that are less than the number requested.)

	2. Link your comparison values to the generated slots, and the module will start working.

	Note1:  If you delete a link while it is "true", the program will return the slot to "false";
	Note2:  If the linked point becomes inValid, it will not be used by the logic.
	Note3:  The Max number of variables you can add is 60.

	**/

	private int count = 1;      
	private boolean ValFlag1;
	private BStatusBoolean InVal;


	public void onStart() throws Exception
	{
		updateTimer();  
	}

	public void onVariableCount(BDouble NV) throws Exception
	{                                              
		if(NV.getDouble() > 60.0) getNumberOfValues().setValue(60.0);
		else getNumberOfValues().setValue(NV.getDouble());      
		slots(getNumberOfValues().getValue());
	}                                         

	public void onExecute() throws Exception
	{              
		try
		{
			if(!Sys.atSteadyState() || !isRunning())
			{
				logger.trace("\n\t\t" + getSlotPath()	+ "'onExecute()' method  --  'if(!Sys.atSteadyState() || !isRunning())' == true.\n");
				return;
			}
			updateTimer();
		}
		catch (Exception e) 
		{
			logger.error("\n\t\t" + getSlotPath()	+ "\n\t\t'onExecute()' method had an error.\n\t\t" + e.getMessage() + "\n\t\t" + e.getStackTrace());
		}
	}
	
	
	public void onCalculate() throws Exception
	{
		try
		{
			if(!Sys.atSteadyState() || !isRunning())
			{
				logger.trace("\n\t\t" + getSlotPath()	+ "'onCalculate()' method  --  'if(!Sys.atSteadyState() || !isRunning())' == true.\n");
				return;
			}
			
			while (((BObject)get("In_"+count))!=null && !ValFlag1)
			{            
				InVal = ((BStatusBoolean) ((BObject)get("In_"+count)));                        

				/** Tests whether the slot is linked. If not, the value is set to null **/
				if (getProgram().getLinks(getProperty("In_"+count)).length == 0)
				{             
					InVal.setStatusNull(true); 
				} 

				/** Tests whether the slot is true and valid **/
				if (InVal.getValue() && InVal.getStatus().isValid()) ValFlag1=true;

				count++;  
			}

			/** Turns Output On **/
			if (ValFlag1)
			{
				getOut().setValue(true);
				getOut().setStatusNull(false);
				if(getToNull()) {getOutRev().setStatusNull(true);}
				else{getOutRev().setStatusNull(false);}
				getOutRev().setValue(false);

				fireTrue(BBoolean.make(true));
				
				ValFlag1=false;      
			}
			/** Turns Output Off **/
			else
			{
				if(!getToNull())
				{
					getOut().setValue(false); 
					getOutRev().setValue(true);

					getOut().setStatusNull(false); 
					getOutRev().setStatusNull(false);
				}
				else 
				{
					getOut().setStatusNull(true);
					getOutRev().setValue(true);
					getOutRev().setStatusNull(false);
					
				}
				fireFalse(BBoolean.make(true));
			}

			ValFlag1=false;  
			count = 1;
		}
		catch (Exception e) 
		{
			logger.error("\n\t\t" + getSlotPath()	+ "\n\t\t'onCalculate()' method had an error.\n\t\t" + e.getMessage() + "\n\t\t" + e.getStackTrace());
		}
	}
	
	

	public void onStop() throws Exception
	{
		try
		{
			/** If we have a ticket, then cancel it  **/
			if (ticket != null) ticket.cancel();
		}
		catch (Exception e) 
		{
			logger.error("\n\t\t" + getSlotPath()	+ "\n\t\t'onStop()' method had an error.\n\t\t" + e.getMessage() + "\n\t\t" + e.getStackTrace());
		}
	}  

	void updateTimer()
	{        
		if (ticket != null)ticket.cancel();
		// ticket = Clock.schedule(getProgram(), BRelTime.makeSeconds(1), BSuperOr.calculate, null);
		
		if(getTime().getMillis()>0)
		{
		  ticket = Clock.schedule(getProgram(), getTime(), BSuperOr.calculate, null);
		}
		else
		{
		  calculate();
		}
	}    

	Clock.Ticket ticket;      /** Used to manage the current timer **/

	public void slots(double MD) throws Exception
	{
		for(int i=1; i<(MD+1 ); i++)
		{
			if(((BObject)get("In_"+i))==null) {getProgram().add(("In_"+i), new BStatusBoolean(false), Flags.SUMMARY | Flags.EXECUTE_ON_CHANGE);}
		}

		for(int i=(int)MD+1;((BObject)get("In_"+i))!=null;i++)
		{
			if(((BObject)get("In_"+i))!=null) {getProgram().remove("In_"+i);}             
		}
	}


	////////////////////////////////////////////////////////////////
	// Type
	////////////////////////////////////////////////////////////////
	
	public static final Log logger = Log.getLog("axCommunity.SuperOr");

	public Type getType() { return TYPE; }
	public static final Type TYPE = Sys.loadType(BSuperOr.class);

	/** Get the icon. */
	public BIcon getIcon() { return icon; }
	private static final BIcon icon = BIcon.make("local:|module://axCommunity/org/axcommunity/niagara/graphics/SuperOr2.png");

}
