package org.axcommunity.niagara.conversion;

import javax.baja.status.*;
import javax.baja.sys.*;
import javax.baja.util.*;

public class BStatusStringToFormat
  extends BComponent implements Runnable
{

////////////////////////////////////////////////////////////////
// Property "inString"
////////////////////////////////////////////////////////////////

  public static final Property inString = newProperty(0|Flags.EXECUTE_ON_CHANGE|Flags.SUMMARY, new BStatusString("%alarmData.sourceName% is Happy"), null);

  public BStatusString getInString() { return (BStatusString)get(inString); }

  public void setInString(BStatusString v) { set(inString, v, null); }


////////////////////////////////////////////////////////////////
// Property "outBFormat"
////////////////////////////////////////////////////////////////

  public static final Property outBFormat = newProperty(0|Flags.SUMMARY, (BValue)BFormat.TYPE.getInstance(), null);

  public BFormat getOutBFormat() { return (BFormat)get(outBFormat); }

  public void setOutBFormat(BFormat v) { set(outBFormat, v, null); }


////////////////////////////////////////////////////////////////
// Action "execute"
////////////////////////////////////////////////////////////////

  public static final Action execute = newAction(0|Flags.ASYNC, null, null);

  public void execute(){ invoke(execute, null, null); }

  /** Autogenerated delegate for "onExecute" */
  public void doExecute() throws Exception
  {
    try { onExecute(); }
    catch (Throwable t) { throw new Exception(t); }
  }


////////////////////////////////////////////////////////////////
// BComponent Overrides
////////////////////////////////////////////////////////////////

  public void started() throws Exception { try { onStart(); } catch(Throwable t) { throw new Exception(t); } }

  public void stopped() throws Exception { try { onStop(); } catch(Throwable t) { throw new Exception(t); } }

  public void changed(Property prop, Context cx)
  {
    super.changed(prop, cx);
    if (!isRunning()) return;
    if (Flags.isExecuteOnChange(this, prop)) execute();
  }


////////////////////////////////////////////////////////////////
// Runnable
////////////////////////////////////////////////////////////////

  public void run() { System.out.println("Source BProgram did not override run(). Exiting thread."); }


////////////////////////////////////////////////////////////////
// Access
////////////////////////////////////////////////////////////////

  public final BComponent getComponent() { return this; }

  public final BComponent getProgram() { return this; }


////////////////////////////////////////////////////////////////
// Utils
////////////////////////////////////////////////////////////////

  /** Print a string to standard out without a trailing new-line. */
  public void print(String s) { System.out.print(s); System.out.flush(); }

  /** Print a string to standard out with a trailing new-line. */
  public void println(String s) { System.out.println(s); }


////////////////////////////////////////////////////////////////
// ProgramBase Stubs
////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////
// BProgram Source Code
////////////////////////////////////////////////////////////////

  public void onStart() throws Exception
  {
    // start up code here
  }
  
  public void onExecute() throws Exception 
  {
  
    setOutBFormat(BFormat.make(getInString().getValue()))  ;
    
  }
  
  
  public void onStop() throws Exception
  {
    // shutdown code here
  }
  
  //icon for this component
  public BIcon getIcon() { return icon; }
  private static final BIcon icon = BIcon.make("module://axCommunity/org/axcommunity/niagara/graphics/Ronin16.png"); 


////////////////////////////////////////////////////////////////
// Type
////////////////////////////////////////////////////////////////

  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BStatusStringToFormat.class);

}
