package org.axcommunity.niagara.logic;
import javax.baja.status.*;
import javax.baja.sys.*;

public class BBooleanToggle extends BComponent implements Runnable
{

////////////////////////////////////////////////////////////////
// Property "out"
////////////////////////////////////////////////////////////////

  public static final Property out = newProperty(0, new BStatusBoolean(), null);

  public BStatusBoolean getOut() { return (BStatusBoolean)get(out); }

  public void setOut(BStatusBoolean v) { set(out, v, null); }


////////////////////////////////////////////////////////////////
// Property "outBool"
////////////////////////////////////////////////////////////////

  public static final Property outBool = newProperty(0, (BValue)BBoolean.TYPE.getInstance(), null);

  public boolean getOutBool() { return getBoolean(outBool); }

  public void setOutBool(boolean v) { setBoolean(outBool, v, null); }



////////////////////////////////////////////////////////////////
// Action "toggle"
////////////////////////////////////////////////////////////////

  public static final Action toggle = newAction(0|Flags.OPERATOR, null, null);

  public void toggle(){ invoke(toggle, null, null); }

  /** Autogenerated delegate for "onToggle" */
  public void doToggle() throws Exception
  {
    try { onToggle(); }
    catch (Throwable t) { throw new Exception(t); }
  }


////////////////////////////////////////////////////////////////
// BComponent Overrides
////////////////////////////////////////////////////////////////

  public void started() throws Exception { try { onStart(); } catch(Throwable t) { throw new Exception(t); } }

  public void stopped() throws Exception { try { onStop(); } catch(Throwable t) { throw new Exception(t); } }

  public void changed(Property prop, Context cx)
  {
    super.changed(prop, cx);
    if (!isRunning()) return;
    if (Flags.isExecuteOnChange(this, prop)) toggle();
  }


////////////////////////////////////////////////////////////////
// Runnable
////////////////////////////////////////////////////////////////

  public void run() { System.out.println("Source BProgram did not override run(). Exiting thread."); }


////////////////////////////////////////////////////////////////
// Access
////////////////////////////////////////////////////////////////

  public final BComponent getComponent() { return this; }


////////////////////////////////////////////////////////////////
// BProgram Source Code
////////////////////////////////////////////////////////////////

  public void onStart() throws Exception
  {
    // start up code here
  }
  
  
  public void onStop() throws Exception
  {
    // shutdown code here
  }
  public void onToggle() throws Exception
  {
   
  
    getOut().setValue(!getOut().getValue())  ;
  
    setOutBool(getOut().getValue());
  
  }


////////////////////////////////////////////////////////////////
// Type
////////////////////////////////////////////////////////////////

  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BBooleanToggle.class);
  
  //icon for this component
  public BIcon getIcon() { return icon; }
  private static final BIcon icon = BIcon.make("local:|module://axCommunity/org/axcommunity/niagara/graphics/Ronin16.png"); 

}

