package org.axcommunity.niagara.extensions;

import javax.baja.alarm.*;
import javax.baja.alarm.ext.*;
import javax.baja.control.*;
import javax.baja.naming.*;
import javax.baja.status.*;
import javax.baja.sys.*;



/**
 * provide Alarm Ack on parent point of Unacked Alarm 
 * @author    Dean Mynott - Ronin Control Systems Pty Ltd
 * @creation  19 May 2012
 */
public class BUnAckAlarmState extends BPointExtension implements Runnable
{

////////////////////////////////////////////////////////////////
// Runnable
////////////////////////////////////////////////////////////////

  public void run() { System.out.println("Source BProgram did not override run(). Exiting thread."); }

  
  public static final Property unackedAlarm = newProperty(Flags.OPERATOR|Flags.READONLY|Flags.TRANSIENT|Flags.SUMMARY, new BStatusBoolean(),null);
  public BStatusBoolean getUnackedAlarm() { return (BStatusBoolean)get(unackedAlarm); }
  public void setUnackedAlarm(BStatusBoolean v) { set(unackedAlarm,v,null); }


////////////////////////////////////////////////////////////////
// Action "ackAlarm"
////////////////////////////////////////////////////////////////

  public static final Action acknowlege = newAction(0|Flags.OPERATOR, null, null);

  public void acknowlege(){ invoke(acknowlege, null, null); }

  /** Autogenerated delegate for "onAcknowlege" */
  public void doAcknowlege() throws Exception
  {
    try { onAcknowlege(); }
    catch (Throwable t) { throw new Exception(t); }
  }



////////////////////////////////////////////////////////////////
// Type
////////////////////////////////////////////////////////////////
  
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BUnAckAlarmState.class);

/*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

////////////////////////////////////////////////////////////////
//  Constructors
////////////////////////////////////////////////////////////////

  public BUnAckAlarmState()
  {
  }

////////////////////////////////////////////////////////////////
//  Parent checking
////////////////////////////////////////////////////////////////

  /**
   * Forces the parent to be a numeric point.
   */

  public boolean isParentLegal(BComponent parent)
  {
    if (parent instanceof BControlPoint )   
      return true;
    else
      return false;
  } 
  

////////////////////////////////////////////////////////////////
// Update Methods
////////////////////////////////////////////////////////////////

  public void changed(Property p, Context cx)
  {
//   super.changed(p, cx);
//   if(!isRunning())
//    return;
//   if( p.equals(filter) )
//   {
//    BControlPoint parent = getParentPoint();
//    if(parent != null) getParentPoint().execute();
//   }
  }

  /**
   * Called when either me or my parent control point is updated.
   */

  public void onExecute(BStatusValue o, Context cx)
  {  //System.out.println("EXECUTE WAS CALLED" ); 
    BControlPoint parent = getParentPoint(); 
    Action a = parent.getAction ("acknowlege");
    
    if (a == null)     
      {
         //System.out.println("Parent has NO acknowlege slot: adding one ... " ) ;
         parent.add ("acknowlege", (BValue)Sys.getType("program:ProgramAction").getInstance()); 
         
         //add link
         BLink link = makeLink(parent, parent.getSlot("acknowlege"), getSlot("acknowlege") , null);
         add("ack", link);
         link.activate(); 
      }
      
    BStatus status = o.getStatus();
    boolean unacked = status.isUnackedAlarm();    
    //int fl = getFlags(a);
       
    if (unacked)
      {
        getUnackedAlarm().setValue(status.isUnackedAlarm());
       
        Slot s = parent.getSlot("acknowlege");
        parent.setFlags(s, (parent.getFlags(s) & ~Flags.HIDDEN)); 
               
      }
    else
      {
        Slot s = parent.getSlot("acknowlege");
        parent.setFlags(s, (parent.getFlags(s) | Flags.HIDDEN));       
      }
     
   
   }
 





  public void onAcknowlege() throws Exception
  {
 
   BControlPoint   parent = getParentPoint();
   BComponent[]    kids   = parent.getChildComponents();
   BAlarmSourceExt source ;
  
   System.out.println("at least its running ... ");
 
   for(int i=0; i<kids.length; ++i) 
        {
     
         if (kids[i] instanceof BAlarmSourceExt )     // "alarm:AlarmSourceExt"
           {

            BAlarmService alarmService = (BAlarmService)Sys.getService(BAlarmService.TYPE);
            AlarmDbConnection conn = alarmService.getAlarmDb().getDbConnection(null);



            source =  (BAlarmSourceExt)kids[i]; 
            BOrdList list = BOrdList.make(source.getNavOrd () );
            
            //BAlarmService service = (BAlarmService)Sys.getService(BAlarmService.TYPE);
            //BAlarmDatabase db     =  service.getAlarmDb();
            // Get a cursor of alarm records 
            Cursor<BAlarmRecord> cursor = conn.getAlarmsForSource(list);
            while(cursor.next())
              {
              BAlarmRecord record = cursor.get();
              record.setAckState(BAckState.acked);
              alarmService.doAckAlarm(record);
              //  System.out.println(record.toString());
              }
           
            // Clean up
            cursor = null;             

           }
        }
  }


    //icon for this component
    public BIcon getIcon() { return icon; }
        private static final BIcon icon = BIcon.make("module://axCommunity/org/axcommunity/niagara/graphics/Ronin16.png");  


                
////////////////////////////////////////////////////////////////
// Attributes
////////////////////////////////////////////////////////////////
}  


