
package org.axcommunity.niagara.conversion;

import javax.baja.status.*;
import javax.baja.sys.*;

/**
 * The BRelTimeToStatusNumeric takes a RelTime and turns it into Hour or Minutes or Seconds 
 * @author    Dean Mynott       - Ronin Control Systems Pty Ltd
 * @creation  16 June 2011
 */

public class BRelTimeToStatusNumeric
  extends BComponent implements Runnable
{

////////////////////////////////////////////////////////////////
// Property "relTime"
////////////////////////////////////////////////////////////////

  public static final Property relTime = newProperty(0|Flags.EXECUTE_ON_CHANGE|Flags.SUMMARY, (BValue)BRelTime.TYPE.getInstance(), null);

  public BRelTime getRelTime() { return (BRelTime)get(relTime); }

  public void setRelTime(BRelTime v) { set(relTime, v, null); }


////////////////////////////////////////////////////////////////
// Property "seconds"
////////////////////////////////////////////////////////////////

  public static final Property seconds = newProperty(0|Flags.SUMMARY, new BStatusNumeric(), null);

  public BStatusNumeric getSeconds() { return (BStatusNumeric)get(seconds); }

  public void setSeconds(BStatusNumeric v) { set(seconds, v, null); }


////////////////////////////////////////////////////////////////
// Property "minutes"
////////////////////////////////////////////////////////////////

  public static final Property minutes = newProperty(0|Flags.EXECUTE_ON_CHANGE|Flags.SUMMARY, new BStatusNumeric(), null);

  public BStatusNumeric getMinutes() { return (BStatusNumeric)get(minutes); }

  public void setMinutes(BStatusNumeric v) { set(minutes, v, null); }

////////////////////////////////////////////////////////////////
// Property "hours"
////////////////////////////////////////////////////////////////

  public static final Property hours = newProperty(0|Flags.EXECUTE_ON_CHANGE|Flags.SUMMARY, new BStatusNumeric(), null);

  public BStatusNumeric getHours() { return (BStatusNumeric)get(hours); }

  public void setHours(BStatusNumeric v) { set(hours, v, null); }

////////////////////////////////////////////////////////////////
// Action "execute"
////////////////////////////////////////////////////////////////

  public static final Action execute = newAction(0|Flags.ASYNC, null, null);

  public void execute(){ invoke(execute, null, null); }

  /** Autogenerated delegate for "onExecute" */
  public void doExecute() throws Exception
  {
    try { onExecute(); }
    catch (Throwable t) { throw new Exception(t); }
  }


////////////////////////////////////////////////////////////////
// BComponent Overrides
////////////////////////////////////////////////////////////////

  public void started() throws Exception { try { onStart(); } catch(Throwable t) { throw new Exception(t); } }

  public void stopped() throws Exception { try { onStop(); } catch(Throwable t) { throw new Exception(t); } }

  public void changed(Property prop, Context cx)
  {
    super.changed(prop, cx);
    if (!isRunning()) return;
    if (Flags.isExecuteOnChange(this, prop)) execute();
  }


////////////////////////////////////////////////////////////////
// Runnable
////////////////////////////////////////////////////////////////

  public void run() { System.out.println("Source BProgram did not override run(). Exiting thread."); }


////////////////////////////////////////////////////////////////
// Access
////////////////////////////////////////////////////////////////

  public final BComponent getComponent() { return this; }


  /** Print a string to standard out without a trailing new-line. */
  public void print(String s) { System.out.print(s); System.out.flush(); }

  /** Print a string to standard out with a trailing new-line. */
  public void println(String s) { System.out.println(s); }


  public void onStart() throws Exception
  {
    // start up code here
  }
  
  public void onExecute() throws Exception
  {
    getSeconds().setValue(   getRelTime().getSeconds()  );
    getMinutes().setValue(   getRelTime().getMinutes()  );
    getHours().setValue(     getRelTime().getHours()  );
  }
  
  public void onStop() throws Exception
  {
    // shutdown code here
  }
  //icon for this component
  public BIcon getIcon() { return icon; }
  private static final BIcon icon = BIcon.make("local:|module://axCommunity/org/axcommunity/niagara/graphics/Ronin16.png"); 


////////////////////////////////////////////////////////////////
// Type
////////////////////////////////////////////////////////////////

  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BRelTimeToStatusNumeric.class);

}
